spring:  datasource:    url: jdbc:mysql://localhost/commandesdb?createDatabaseIfNotExist=true
    username: root    driver-class-name: com.mysql.jdbc.Driver  jpa:    hibernate:      ddl-auto: update      show-sql: true  application:    name: commande-serviceserver:  port: 8046
#commandeSupplier

spring.cloud.stream:  function:    definition: commandeSupplier;inventoryEventConsumer  bindings:    commandeSupplier-out-0:      destination: order-event    inventoryEventConsumer-in-0:      destination: inventory-event